# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de70a3ec01365f3ffba8c1d41399667dd8a1815cefb2eed1d435c38434cc2302175030ac85a420f8ce43a8c64b62921b3be489d8212c3e8ddad9bdb5834b81ab

test:
  secret_key_base: 729a51bd99b66df58b48df9197e6763661897f213c6590063839558de85de84d2f26950d739562e112b8a63597ec85d253baaa954ac0c049e4db71242d8d0dac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
